// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env.DATABASE_URL,
//   },
// });


import "dotenv/config"; // charge automatiquement le .env
import { defineConfig, env } from "prisma/config";

/**
 * Configuration Prisma v7
 * Doc officielle : https://pris.ly/d/config-datasource
 *
 * En v7, l'URL de connexion se déclare ici via datasource.url
 * Le bloc migrate.adapter n'est PAS nécessaire pour PostgreSQL standard
 */
export default defineConfig({
  schema: "prisma/schema.prisma", // Chemin vers le schéma Prisma

  migrations: {
    path: "prisma/migrations", // Dossier des fichiers de migration
    //seed: "ts-node prisma/seed.ts", // Commande de seed
    // ts-node pour exécuter le seed TypeScript directement
    seed: "ts-node -r tsconfig-paths/register prisma/seed.ts",
  },

  datasource: { // Connexion à la base de données
    url: env("DATABASE_URL"), // lit DATABASE_URL depuis le .env
  },
});
