services:
  - type: web
    name: afrikcse-afrikvoyage
    runtime: node
    region: frankfurt
    plan: free

    buildCommand: npm install && npx prisma generate --early-access && npm run build

    # Migration + démarrage séparés avec les bons flags
    startCommand: npx prisma migrate deploy --early-access && node dist/server.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: afrikcse-afrikvoyage
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: KKIAPAY_PUBLIC_KEY
        sync: false
      - key: KKIAPAY_PRIVATE_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false

databases:
  - name: afrikcse-afrikvoyage
    databaseName: afrikcse-afrikvoyage
    user: afrikcse_user
    region: frankfurt
    plan: free